### ISSUE TITLE
doesn't appear to work (on mac?)

### ISSUE THREAD

**Issue by darrencruse** [Nurtak/ObjectGraphVisualization#3]
on a macbook I downloaded the OGV.3.1.Java.Runnable.zip but unzipping and running with java -jar just seems to open what looks like an empty hello world skeleton app?

<img width="679" alt="Screen Shot 2019-07-04 at 9 59 21 AM" src="https://user-images.githubusercontent.com/1283688/60675743-b5678000-9e42-11e9-8ba2-807d40dba851.png">

<img width="405" alt="Screen Shot 2019-07-04 at 9 58 47 AM" src="https://user-images.githubusercontent.com/1283688/60675757-c0221500-9e42-11e9-939f-8efe7c1822bb.png">

**Comment by shathor** [comment]
There's certainly an issue with the runnable jar, not only on Mac. The files are in the jar, but something else is amiss. I'll get to it in a bit.

**Comment by shathor** [comment]
Ok, I mistakenly tried to run it with the OpenJDK, which does not contain JavaFX. When I run it with the Oracle JDK u144, it starts fine on Windows.
Could you also try a newer version of the JDK on Mac?
